---
title: "World Cup Analysis and Predictions"
author: "Chase Webber"
subtitle: Summaries and Predictions w/ Classification
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}

# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')


```

```{r setup-2}

# Always print this out before your assignment
sessionInfo()
getwd()

```


<!-- ### start answering your problem set here -->
<!-- You may export your homework in either html or pdf, with the former usually being easier. 
     To export or compile your Rmd file: click above on 'Knit' then 'Knit to HTML' -->
<!-- Be sure to submit both your .Rmd file and the compiled .html or .pdf file for full credit -->

install.packages('vtable')
install.packages('caret')


```{r setup-3}

# load all your libraries in this chunk 
library('tidyverse')
library("partykit")
library('vtable')

library('caret')


library('yardstick')
library('ISLR')
library('plotROC')
library('plotly')



library('lubridate')

library('scales')
library('data.table')

library("PerformanceAnalytics")
library("rpart")
library("rpart.plot")
library('dplyr')


library("randomForest")

library("rsample")
library("randomForestExplainer")

library("DALEX")
library("pdp")

library("visNetwork")
library("sparkline")

library("ggplot2")
library("ggridges")
# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 

```



## Question 1

1a) Text response to part a. 

```{r}

fifa <- read.csv("international_matches.csv")

# Make variable for total goals scored in a game
fifa_df <- fifa %>% 
  mutate(total_goals = (fifa$home_team_score + fifa$away_team_score)) 

# Mutated date variable, arranged by current
fifa_current <- fifa_df %>% 
  mutate(neutral_location = as.logical(neutral_location)) %>% 
  arrange(desc(date)) 

# Creating home and away team tables
home_rank <- fifa_current %>% 
  select(date, home_team, home_team_score, away_team_score, home_team_continent, home_team_fifa_rank, home_team_total_fifa_points, home_team_score, tournament, neutral_location, home_team_result, home_team_goalkeeper_score, home_team_mean_defense_score, home_team_mean_midfield_score, home_team_mean_offense_score) %>% 
  rename(country = home_team, team_score = home_team_score, opponent_score = away_team_score, country_rank = home_team_fifa_rank, continent = home_team_continent, fifa_points = home_team_total_fifa_points, score = home_team_score, tournament = tournament, neutral_location = neutral_location, home_team_result = home_team_result, goalkeeper_score = home_team_goalkeeper_score, defense_score = home_team_mean_defense_score, midfield_score = home_team_mean_midfield_score, offense_score = home_team_mean_offense_score)

away_rank <- fifa_current %>% 
  select(date, away_team, away_team_score, home_team_score, away_team_continent, away_team_fifa_rank, away_team_total_fifa_points, away_team_score, tournament, neutral_location, home_team_result, away_team_goalkeeper_score, away_team_mean_defense_score, away_team_mean_midfield_score, away_team_mean_offense_score) %>% 
  rename(country = away_team, team_score = away_team_score, opponent_score = home_team_score, country_rank = away_team_fifa_rank, continent = away_team_continent, fifa_points = away_team_total_fifa_points, score = away_team_score, tournament = tournament, neutral_location = neutral_location, home_team_result = home_team_result, goalkeeper_score = away_team_goalkeeper_score, defense_score = away_team_mean_defense_score, midfield_score = away_team_mean_midfield_score, offense_score = away_team_mean_offense_score)

home_rank <- home_rank %>% 
  mutate(home_away = 'H')
away_rank <- away_rank %>% 
  mutate(home_away = 'A')

# Combining home and away tables
ranking_all <- drop_na(rbind(home_rank, away_rank))

# Mutating variables
ranking_all <- ranking_all %>% 
  mutate(team= as.factor(country),
         tournament = as.factor(tournament),
         neutral_location = as.logical(neutral_location),
         home_away = as.factor(home_away),
         continent=as.factor(continent),
         country_rank = as.factor(country_rank),
         home_team = as.logical(ifelse(home_away=='H','TRUE', 'FALSE')),
         offense_score = as.numeric(offense_score),
         team_win = as.logical(ifelse(score>opponent_score, 'TRUE', 'FALSE')))

# Create train and test sets
ranking_all_split <- initial_split(ranking_all, prop = 0.75) 

ranking_train <- training(ranking_all_split)
ranking_test <- testing(ranking_all_split)

# Creating table w/ home and away that also includes null values for summaries
ranking_all_na <- rbind(home_rank, away_rank)

ranking_all_na <- ranking_all_na %>% 
  mutate(team= as.factor(country),
         tournament = as.factor(tournament),
         neutral_location = as.factor(neutral_location))


```

```{r}

latest_to_earliest_matchess <-
  fifa_df %>% 
  mutate(date = ymd(date), neutral_location = as.logical(neutral_location)) %>% 
  arrange(desc(date)) 

home <-
  latest_to_earliest_matchess %>% 
  select(date, home_team, home_team_fifa_rank) %>% 
  rename(Country = home_team, current_country_rank = home_team_fifa_rank)

# Get the ranking of all away teams
away <-
  latest_to_earliest_matchess %>% 
  select(date, away_team, away_team_fifa_rank) %>% 
  rename(Country = away_team, current_country_rank = away_team_fifa_rank)

# Combine both data frames into one
fifa_ranking <- rbind(home, away)

# Get the latest ranking of each country based on their most recent match
latest_fifa_ranking <-
  fifa_ranking %>% 
  arrange(Country, desc(date)) %>% 
  group_by(Country) %>% 
  mutate(row_number = row_number(Country)) %>% 
  filter(row_number == 1) %>% 
  select(-row_number, -date) %>% 
  arrange(current_country_rank)
  
head(latest_fifa_ranking, 30)


```



1b) Response to part b. 

```{r}

# Show dimensions
dim(ranking_all)
dim(ranking_all_na)

```


## Question 2



```{r}
# Pie chart for home teams

ranking_all_nn <- ranking_all %>% filter(neutral_location == FALSE)

ggplot(data = ranking_all_nn, aes(x="", y=home_team_result, fill=home_team_result)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)

```




```{r}

# Only keep world cup (including qualifier) matches

world_cup_t <- ranking_train %>% filter(grepl('FIFA World Cup', tournament))
world_cup_s <- ranking_test %>% filter(grepl('FIFA World Cup', tournament))

```

```{r}

# Creating tables that keep all world cups and top 16 that show rankings from 2018 on


world_cup_t <- with(ranking_train, ranking_train[(date >= "2018-01-01"), ])

world_cup_2022_tr <- world_cup_t[world_cup_t$team %in% c('Qatar', 'Ecuador', 'Senegal', 'Netherlands', 'England', 'IR Iran', 'USA', 'Wales', 'Argentina', 'Saudi Arabia', 'Mexico', 'Poland', 'France', 'Australia', 'Denmark', 'Tunisia', 'Spain', 'Costa Rica', 'Germany', 'Japan', 'Belgium', 'Canada', 'Morocco', 'Croatia', 'Brazil', 'Serbia', 'Switzerland', 'Cameroon', 'Portugal', 'Ghana', 'Uruguay', 'Korea Republic'), ]

world_cup_2022_16_t <- world_cup_t[world_cup_t$team %in% c('Ecuador', 'Senegal', 'Netherlands', 'England', 'USA', 'Argentina', 'Poland', 'France', 'Australia', 'Spain', 'Japan', 'Morocco', 'Croatia', 'Brazil', 'Switzerland', 'Portugal'), ]


world_cup_s <- with(ranking_test, ranking_test[(date >= "2018-01-01"), ])

world_cup_2022_st <- world_cup_s[world_cup_s$team %in% c('Qatar', 'Ecuador', 'Senegal', 'Netherlands', 'England', 'IR Iran', 'USA', 'Wales', 'Argentina', 'Saudi Arabia', 'Mexico', 'Poland', 'France', 'Australia', 'Denmark', 'Tunisia', 'Spain', 'Costa Rica', 'Germany', 'Japan', 'Belgium', 'Canada', 'Morocco', 'Croatia', 'Brazil', 'Serbia', 'Switzerland', 'Cameroon', 'Portugal', 'Ghana', 'Uruguay', 'Korea Republic'), ]

world_cup_2022_16_s <- world_cup_s[world_cup_s$team %in% c('Ecuador', 'Senegal', 'Netherlands', 'England', 'USA', 'Argentina', 'Poland', 'France', 'Australia', 'Spain', 'Japan', 'Morocco', 'Croatia', 'Brazil', 'Switzerland', 'Portugal'), ]







```



```{r}

# Creating variables and table for classification model

world_cup_t <- ranking_train %>% filter(grepl('FIFA World Cup', tournament))
world_cup_s <- ranking_test %>% filter(grepl('FIFA World Cup', tournament))

world_cup_t <- with(ranking_train, ranking_train[(date >= "2018-01-01"), ])

world_cup_2022_16_t <- world_cup_t[world_cup_t$team %in% c('Ecuador', 'Senegal', 'Netherlands', 'England', 'USA', 'Argentina', 'Poland', 'France', 'Australia', 'Spain', 'Japan', 'Morocco', 'Croatia', 'Brazil', 'Switzerland', 'Portugal'), ]

world_cup_s <- with(ranking_test, ranking_test[(date >= "2018-01-01"), ])

world_cup_2022_16_s <- world_cup_s[world_cup_s$team %in% c('Ecuador', 'Senegal', 'Netherlands', 'England', 'USA', 'Argentina', 'Poland', 'France', 'Australia', 'Spain', 'Japan', 'Morocco', 'Croatia', 'Brazil', 'Switzerland', 'Portugal'), ]

clean_16cc_t <- data.frame(world_cup_2022_16_t)

clean_16cc_s <- data.frame(world_cup_2022_16_s)

clean_16_cw_t <- clean_16cc_t %>% mutate(
  continent = as.factor(continent),
  goalkeeper_score = as.numeric(goalkeeper_score),
  defense_score = as.numeric(defense_score),
  midfield_score = as.numeric(midfield_score),
  offense_score = as.numeric(offense_score),
  team = as.factor(team),
  team_win = as.factor(team_win)
) %>% select(
  -home_team, -date, -country, -score, -opponent_score, -country_rank, -fifa_points, -tournament, -neutral_location, -home_team_result
)

clean_16_cw_s <- clean_16cc_s %>% mutate(
  continent = as.factor(continent),
  goalkeeper_score = as.numeric(goalkeeper_score),
  defense_score = as.numeric(defense_score),
  midfield_score = as.numeric(midfield_score),
  offense_score = as.numeric(offense_score),
  team = as.factor(team),
  team_win = as.factor(team_win)
) %>% select(
  -home_team, -date, -country, -score, -opponent_score, -country_rank, -fifa_points, -tournament, -neutral_location, -home_team_result
)


```



```{r}

#Classification model

logit_fitc_t <- glm(team_win ~ team + home_away + goalkeeper_score + 
                      defense_score + midfield_score + offense_score,
                  family = binomial,
                  data = clean_16_cw_t)

summary(logit_fitc_t)
exp(logit_fitc_t$coefficients)


```



```{r}

# Creating rankings from model

fifa <- fifa[fifa$home_team %in% c('Ecuador', 'Senegal', 'Netherlands', 'England', 'USA', 'Argentina', 'Poland', 'France', 'Australia', 'Spain', 'Japan', 'Morocco', 'Croatia', 'Brazil', 'Switzerland', 'Portugal'), ]

fifa <- fifa[fifa$away_team %in% c('Ecuador', 'Senegal', 'Netherlands', 'England', 'USA', 'Argentina', 'Poland', 'France', 'Australia', 'Spain', 'Japan', 'Morocco', 'Croatia', 'Brazil', 'Switzerland', 'Portugal'), ]

latest_to_earliest_matches <-
  fifa %>% 
  mutate(date = ymd(date), neutral_location = as.logical(neutral_location)) %>% 
  arrange(desc(date)) 

all_home <-
  latest_to_earliest_matches %>% 
  select(date, home_team, home_team_mean_offense_score, home_team_goalkeeper_score, home_team_mean_defense_score, home_team_mean_midfield_score) %>% 
  rename(team = home_team, offense_rating = home_team_mean_offense_score, goalkeeper_score = home_team_goalkeeper_score, defense_rating = home_team_mean_defense_score, midfield_rating = home_team_mean_midfield_score)

all_away <-
  latest_to_earliest_matches %>% 
  select(date, away_team, away_team_mean_offense_score, away_team_goalkeeper_score, away_team_mean_defense_score, away_team_mean_midfield_score) %>% 
  rename(team = away_team, offense_rating = away_team_mean_offense_score, goalkeeper_score = away_team_goalkeeper_score, defense_rating = away_team_mean_defense_score, midfield_rating = away_team_mean_midfield_score)

all_rating <- drop_na(rbind(all_home, all_away))

all_rating <- all_rating %>% arrange(team, desc(date)) %>% 
  group_by(team) %>% 
  mutate(row_number = row_number(team),
         model_score = (1.024*goalkeeper_score) + (1.168*defense_rating) + (0.854*midfield_rating) + (1.003*offense_rating)) %>% 
  filter(row_number == 1) %>% 
  arrange(-model_score) %>% 
  select(-date, -row_number, -offense_rating, -goalkeeper_score, -defense_rating,-midfield_rating)

head(all_rating, 10)

```



```{r}
 

# AUC for train
scoresc_t <- predict(logit_fitc_t,
                  type = "response", 
                  data = clean_16_cw_t)

results_trainc_t <- tibble(
  'true_classc_t' = as.factor(clean_16_cw_t$team_win),
  'prob_eventc_t' =  scoresc_t,
  'prob_not_eventc_t' = 1 - scoresc_t,
  'pred_classc_t' = as.factor(ifelse(scoresc_t > 0.2,
                                 "Yes","No"))
)


p_t <- ggplot(results_trainc_t, 
            aes(m = prob_eventc_t, d = true_classc_t)) + 
  geom_roc(labelsize = 3.5, 
           cutoffs.at = 
             c(0.99,0.9,0.7,0.5,0.3,0.1,0)) +
  theme_minimal(base_size = 16)
print(p_t)
calc_auc(p_t)


# AUC for test
logit_fitc_s<- glm(team_win ~ team + home_away + goalkeeper_score + 
                      defense_score + midfield_score + offense_score,
                  family = binomial,
                  data = clean_16_cw_s)


scoresc_s <- predict(logit_fitc_s,
                  type = "response", 
                  data = clean_16_cw_s)

results_trainc_s <- tibble(
  `true_classc_s` = as.factor(clean_16_cw_s$team_win),
  `prob_eventc_s` =  scoresc_s,
  `prob_not_eventc_s` = 1 - scoresc_s,
  `pred_classc_s` = as.factor(ifelse(scoresc_s > 0.2,
                                 "Yes","No"))
)

p_s <- ggplot(results_trainc_s, 
            aes(m = prob_eventc_s, d = true_classc_s)) + 
  geom_roc(labelsize = 3.5, 
           cutoffs.at = 
             c(0.99,0.9,0.7,0.5,0.3,0.1,0)) +
  theme_minimal(base_size = 16)
print(p_s)
calc_auc(p_s)


```

